configure: Introduce a check for preemtive kernels
Signed-off-by: Michal Mielewczyk <michal.mielewczyk@huawei.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,7 @@
 #!/bin/bash
 #
 # Copyright(c) 2012-2022 Intel Corporation
+# Copyright(c) 2024 Huawei Technologies
 # SPDX-License-Identifier: BSD-3-Clause
 #
 
@@ -24,6 +25,7 @@ check_util sed
 check_util make
 check_util gcc
 check_util lsblk
+check_util uname
 
 SCRIPTPATH=`dirname $0`
 SCRIPTPATH=`realpath $SCRIPTPATH`
@@ -45,6 +47,12 @@ fi
 if [ ! -e /lib/modules/$(uname -r)/build/ &> /dev/null ] && [ "$KERNEL_DIR" == "" ]
 then
 	echo >&2 "Error: missing kernel headers and/or kernel devel"
+	MISSING_TOOLS=1
+fi
+
+if [ uname --kernel-version | grep -q "PREEMPT_RT\|PREEMPT_DYNAMIC" ]
+then
+	echo >&2 "Error: Preemptive kernel detected"
 	MISSING_TOOLS=1
 fi
 
